language: php

install:
   - composer self-update
   - composer install

php:
  - 7.0
  - 5.6

before_script:
  - composer install --dev
  - composer require symfony/framework-bundle:dev-master

script:
  - phpunit --configuration travis.phpunit.xml
