language: php

install:
   - composer self-update
   - composer update --prefer-dist --no-interaction

php:
  - 7.0
  - 5.6

before_script:
  - composer install --dev
  - composer require symfony/symfony:3.1.*

script:
  - phpunit --configuration travis.phpunit.xml
